<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="testconfig.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\HamsterWheel.Flows\HamsterWheel.Flows.csproj"/>
        <ProjectReference Include="..\..\src\HamsterWheel.Flows.Api\HamsterWheel.Flows.Api.csproj"/>
    </ItemGroup>

</Project>
