<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Cronos"/>
        <PackageReference Include="HamsterWheel.Data.Mapper" />
        <PackageReference Include="HamsterWheel.HLinq"/>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\HamsterWheel.Flows.Abstractions\HamsterWheel.Flows.Abstractions.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <!--Flow templates-->
        <EmbeddedResource Include="Templates\HamsterAscii.txt">
            <Link>Templates\HamsterAscii.txt</Link>
            <LogicalName>flows:template:HamsterAscii.txt</LogicalName>
        </EmbeddedResource>
    </ItemGroup>

</Project>
