<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
        <PackageReference Include="FluentValidation"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\HamsterWheel.Flows\HamsterWheel.Flows.csproj"/>
    </ItemGroup>

</Project>
